import tokenize
from io import BytesIO, StringIO
import contextlib
import importlib

class tamilppCompiler:
    def __init__(self, lang="tamil"):
        self.lang = lang
        try:
            # Dynamically loads dictionaries/tamil_dic.py, hindi_dic.py, etc.
            module = importlib.import_module(f"dictionaries.{self.lang}_dic")
            self.translation_map = module.dictionary
        except ModuleNotFoundError:
            print(f"⚠️ Dictionary for '{self.lang}' not found. Defaulting to Python.")
            self.translation_map = {}

    def translate(self, code):
        tokens = list(tokenize.tokenize(BytesIO(code.encode('utf-8')).readline))
        new_tokens = []

        for token in tokens:
            if token.string in ('அமை', 'amai', 'set'): # You can move this to the dictionaries later too
                continue

            if token.type == tokenize.NAME:
                translated = self.translation_map.get(token.string.lower(), token.string)
            else:
                translated = token.string

            new_tokens.append(tokenize.TokenInfo(token.type, translated, token.start, token.end, token.line))

        return tokenize.untokenize(new_tokens).decode('utf-8')

    def run(self, code):
        python_code = self.translate(code)
        output_buffer = StringIO()
        try:
            with contextlib.redirect_stdout(output_buffer):
                exec(python_code, {})
            return output_buffer.getvalue()
        except Exception as e:
            return f"❌ Runtime Error: {e}"

    def compile(self, code, output_file):
        python_code = self.translate(code)
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(f"# Generated by Polyglot Compiler ({self.lang})\n")
            f.write(python_code)
        return python_code