import os
import sys
import tokenize
import traceback
import importlib
from io import BytesIO, StringIO
from contextlib import redirect_stdout

# Ensures Vercel can find your dictionary files
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

class PolyglotCompiler:
    def __init__(self, lang="tamil"):
        self.lang = lang
        try:
            module = importlib.import_module(f"dictionaries.{self.lang}_dic")
            self.translation_map = module.dictionary
        except Exception:
            self.translation_map = {}

    def translate(self, code):
        try:
            tokens = list(tokenize.tokenize(BytesIO(code.encode('utf-8')).readline))
            new_tokens = []

            for token in tokens:
                if token.string in ('அமை', 'amai', 'set'):
                    continue
                if token.type == tokenize.NAME:
                    translated = self.translation_map.get(token.string.lower(), token.string)
                else:
                    translated = token.string

                new_tokens.append(tokenize.TokenInfo(token.type, translated, token.start, token.end, token.line))

            return tokenize.untokenize(new_tokens).decode('utf-8')
        except tokenize.TokenError as e:
            raise Exception(f"Syntax Error during translation: {e}")

    def run(self, code, user_inputs=""):
        try:
            python_code = self.translate(code)
        except Exception as e:
            return f"❌ Translation Error: {e}"
        
        output_buffer = StringIO()
        
        # Prepare the inputs from the web text box
        input_lines = user_inputs.split('\n') if user_inputs else []
        
        # The Pro-Grade Input Handler
        def mock_input(prompt=""):
            if prompt:
                output_buffer.write(str(prompt)) # Print the prompt to the terminal
            if input_lines:
                return input_lines.pop(0)
            return "" # Safe fallback if user forgot to provide enough inputs
        
        # Create a safe, isolated environment for the code to run in
        execution_globals = {
            "__builtins__": __builtins__.copy() if isinstance(__builtins__, dict) else dict(__builtins__.__dict__)
        }
        execution_globals["__builtins__"]["input"] = mock_input
        
        try:
            # Safely capture print statements
            with redirect_stdout(output_buffer):
                exec(python_code, execution_globals)
            return output_buffer.getvalue()
        except Exception as e:
            # If the user's code crashes, grab the exact Python error trace!
            error_msg = traceback.format_exc()
            return f"❌ Runtime Error:\n{error_msg}"

    def compile(self, code, output_file):
        python_code = self.translate(code)
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(f"# Generated by Polyglot Compiler ({self.lang})\n")
            f.write(python_code)
        return python_code
